[package]
name = "chatr"
version = "0.1.0"
authors = ["Hamza"]
edition = "2018"

[workspace]

members = [
    "backend",
    "frontend"
]

[dependencies]
tokio = { version = "0.2", features = ["macros"] }
#warp = "0.2"
backend = { path = "backend" }
