name: Lint & Format
on:
  push:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt, clippy
          target: wasm32-unknown-unknown

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            cargo-${{ runner.os }}-

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run clippy on backend & common (linux target)
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          toolchain: nightly
          args: -p backend -p common -- -D warnings

      - name: Run clippy on frontend & common (wasm target)
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          toolchain: nightly
          target: wasm32-unknown-unknown
          args: -p frontend -p common -- -D warnings
